CREATE TYPE "user_role" AS ENUM (
  'mahasiswa',
  'penjual'
);

CREATE TYPE "order_status" AS ENUM (
  'menunggu_konfirmasi',
  'diterima',
  'ditolak',
  'diproses',
  'siap_diambil',
  'selesai',
  'dibatalkan'
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campus_id" varchar(50) UNIQUE NOT NULL,
  "name" varchar(100) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "password" varchar(255),
  "role" user_role NOT NULL,
  "profile_image" varchar(255),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "canteens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" bigint NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" text,
  "location" varchar(255),
  "image_url" varchar(255),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "menu_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "canteen_id" bigint NOT NULL,
  "category_id" bigint,
  "name" varchar(150) NOT NULL,
  "description" text,
  "price" decimal(12,2) NOT NULL,
  "image_url" varchar(255),
  "is_available" boolean NOT NULL DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "carts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint UNIQUE NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "cart_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" bigint NOT NULL,
  "menu_item_id" bigint NOT NULL,
  "quantity" int NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "orders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "canteen_id" bigint NOT NULL,
  "order_number" varchar(30) UNIQUE NOT NULL,
  "status" order_status NOT NULL DEFAULT 'menunggu_konfirmasi',
  "note" text,
  "total_amount" decimal(12,2) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "order_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "menu_item_id" bigint NOT NULL,
  "menu_name" varchar(150) NOT NULL,
  "price" decimal(12,2) NOT NULL,
  "quantity" int NOT NULL,
  "subtotal" decimal(12,2) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

ALTER TABLE "canteens" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu_items" ADD FOREIGN KEY ("canteen_id") REFERENCES "canteens" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu_items" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("canteen_id") REFERENCES "canteens" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;
