/**
 * Kode kesalahan yang dikirim pada `error.code`.
 *
 * Aplikasi klien sebaiknya bercabang berdasarkan kode ini, bukan teks pesan,
 * karena teks pesan dapat berubah sewaktu-waktu.
 */
export const ERROR_CODES = Object.freeze({
  // Umum
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  // Autentikasi dan otorisasi
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_GOOGLE_TOKEN: 'INVALID_GOOGLE_TOKEN',
  EMAIL_DOMAIN_NOT_ALLOWED: 'EMAIL_DOMAIN_NOT_ALLOWED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  NOT_RESOURCE_OWNER: 'NOT_RESOURCE_OWNER',
  DEV_LOGIN_DISABLED: 'DEV_LOGIN_DISABLED',

  // Kantin dan menu
  CANTEEN_NOT_FOUND: 'CANTEEN_NOT_FOUND',
  CANTEEN_CLOSED: 'CANTEEN_CLOSED',
  SELLER_HAS_NO_CANTEEN: 'SELLER_HAS_NO_CANTEEN',
  MENU_NOT_FOUND: 'MENU_NOT_FOUND',
  MENU_UNAVAILABLE: 'MENU_UNAVAILABLE',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',

  // Keranjang
  CART_EMPTY: 'CART_EMPTY',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_DIFFERENT_CANTEEN: 'CART_DIFFERENT_CANTEEN',

  // Pesanan
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INVALID_ORDER_STATUS_TRANSITION: 'INVALID_ORDER_STATUS_TRANSITION',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
});

export default ERROR_CODES;
